version: '3'
networks:
  default:
    external:
      name: localdev_default

services:
  orderservice:
    image: orderservice
    hostname: orderservice
    container_name: orderservice
    environment:
      - SPRING_PROFILES_ACTIVE=localdev
    ports:
    - 127.0.0.1:9086:8080
